### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by seghier** [soft-matter/pimsviewer#15]
hello
how to install this in python ?

**Comment by seghier** [comment]
i finally install it after download and installing : scikit_image-0.13.0-cp27-cp27m-win_amd64.whl
the problem now the code don't work .
import pims
from pimsviewer import Viewer
viewer = Viewer(pims.open('C:/outtest/Nouveau dossier')
viewer.show()
---
my folder have png sequence and i got error message : 
    viewer.show()
         ^
SyntaxError: invalid syntax

**Comment by rbnvrw** [comment]
Thank you for your report. Could you please tell us the steps you took in trying to install pims and pimsviewer?

Also, could you try installing pims using anaconda? See this page for more information: http://soft-matter.github.io/pims/v0.4/install.html

The command you need is `conda install -c conda-forge pims`. Then try to reinstall pimsviewer.

**Comment by seghier** [comment]
hi
i tried first with pip than i tried with pycharm without success, after that i tried with setup.py but always error .
after  installing :scikit_image-0.13.0-cp27-cp27m-win_amd64.whl ; it installed but i got error when i run the script.
is the problem with the code or something missing ?
import pims
from pimsviewer import Viewer
viewer = Viewer(pims.open('C:/outtest/sequence')) #(sequence is the folder where the png animation located ; a00.png ; a001.png .....)
viewer.show()

**Comment by caspervdw** [comment]
@seghier Thanks for the error report. Please surround your codeblocks with \`\`\` , so that your posts become a bit more readable. I edited them for you.

Looking at the exception trace, this issue is the same as https://github.com/soft-matter/pims/issues/276 which has been solved yesterday. As @rbnvrw suggested, we recommend using `conda` for installation. It comes with Anaconda which can be found over [here](https://www.anaconda.com/download/). This installs precompiled packages which is especially useful on Windows.

Please update pims to the most recent version (either via conda or pip) and the metaclass problem should go away.

**Comment by seghier** [comment]
thanks
it work now but it read just one file; how i can play png sequence ?
